-- SERVER-CONFIG-DATA PORTS

if not SERVER_CONFIG then 
    SERVER_CONFIG = {}
end

SERVER_CONFIG.SRS_DIRECTORY = "C:\\Program Files\\DCS-SimpleRadio-Standalone"
SERVER_CONFIG.SRS_PORT = 10406 -- LOCAL SRS PORT - DEFAULT IS 5002
SERVER_CONFIG.SRS_EXECUTABLE = "DCS-SR-ExternalAudio.exe"

if not STTS then 
    STTS = {}
end

STTS.DIRECTORY = SERVER_CONFIG.SRS_DIRECTORY
STTS.SRS_PORT = SERVER_CONFIG.SRS_PORT
STTS.EXECUTABLE = SERVER_CONFIG.SRS_EXECUTABLE
